# Generated by Django 5.2.12 on 2026-03-11 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название задачи')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('task_type', models.CharField(choices=[('fixed', 'Фиксированная'), ('additional', 'Дополнительная')], default='fixed', max_length=20, verbose_name='Тип задачи')),
                ('planned_hours', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Плановые часы')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Заполняется преподавателем при выполнении', max_digits=7, null=True, verbose_name='Фактические часы')),
                ('status', models.CharField(choices=[('assigned', 'Назначена'), ('in_progress', 'В работе'), ('completed', 'Выполнена'), ('approved', 'Подтверждена'), ('rejected', 'Отклонена')], default='assigned', max_length=20, verbose_name='Статус')),
                ('result', models.TextField(blank=True, default='', help_text='Например, название статьи, ссылка на публикацию', verbose_name='Результат')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('rejection_reason', models.TextField(blank=True, default='', verbose_name='Причина отклонения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='core.academicyear', verbose_name='Учебный год')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='core.taskcategory', verbose_name='Категория')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
            },
        ),
    ]
