# Generated by Django 5.2.12 on 2026-05-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending_approval', 'Ожидает утверждения'), ('assigned', 'Назначена'), ('in_progress', 'В работе'), ('completed', 'Выполнена'), ('approved', 'Подтверждена'), ('rejected', 'Возвращена на доработку'), ('declined', 'Не утверждена')], default='assigned', max_length=20, verbose_name='Статус'),
        ),
    ]
