# Generated by Django 5.2.12 on 2026-05-08 08:25

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_worktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(choices=[('MAIN', 'Основное место работы'), ('INTERNAL_COMBINING', 'Внутреннее совместительство'), ('EXTERNAL_COMBINING', 'Внешнее совместительство'), ('HOURLY', 'На условиях почасовой оплаты труда')], max_length=30, verbose_name='Вид занятости')),
                ('rate', models.DecimalField(blank=True, choices=[(Decimal('1.00'), '1.0 (полная ставка)'), (Decimal('0.75'), '0.75'), (Decimal('0.50'), '0.5'), (Decimal('0.25'), '0.25')], decimal_places=2, help_text='Заполняется для всех видов занятости, кроме почасовой', max_digits=3, null=True, verbose_name='Доля ставки')),
                ('teaching_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Заполняется по выгрузке из 1С.', max_digits=7, verbose_name='Учебная нагрузка (часов из 1С)')),
                ('protocol_number', models.CharField(blank=True, default='', help_text='Например: «1»', max_length=50, verbose_name='Номер протокола утверждения')),
                ('protocol_date', models.DateField(blank=True, null=True, verbose_name='Дата протокола')),
                ('is_active', models.BooleanField(default=True, help_text='Если позиция закрыта (декрет, увольнение и т.п.) — снимите флаг', verbose_name='Активна')),
                ('notes', models.TextField(blank=True, default='', help_text='Например: «декретный отпуск», «творческий отпуск»', verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_positions', to='core.academicyear', verbose_name='Учебный год')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_positions', to='core.position', verbose_name='Должность')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_positions', to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Позиция преподавателя',
                'verbose_name_plural': 'Позиции преподавателей',
                'ordering': ['user__full_name', 'academic_year', 'employment_type'],
            },
        ),
    ]
