# Generated by Django 5.2.12 on 2026-05-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_teacherposition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rate',
        ),
        migrations.AddField(
            model_name='user',
            name='academic_title',
            field=models.CharField(blank=True, default='', help_text='Например: «кандидат наук, доцент». Используется в шапке выгрузки плана.', max_length=255, verbose_name='Учёное звание и степень'),
        ),
    ]
