# Generated by Django 5.2.12 on 2026-05-15 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_position_remove_user_rate_and_more'),
        ('core', '0003_teachingactivitytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherposition',
            name='teaching_load_imported_at',
            field=models.DateTimeField(blank=True, help_text='Дата и время последнего импорта выгрузки 1С для этой позиции', null=True, verbose_name='Учебная нагрузка загружена'),
        ),
        migrations.CreateModel(
            name='TeachingLoadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(help_text='Название дисциплины из выгрузки 1С', max_length=300, verbose_name='Дисциплина')),
                ('semester', models.PositiveSmallIntegerField(help_text='Номер семестра (1–8)', verbose_name='Семестр')),
                ('hours', models.DecimalField(decimal_places=2, help_text='Плановое количество часов из выгрузки 1С', max_digits=7, verbose_name='Часы (план)')),
                ('group_number', models.CharField(blank=True, default='', help_text='Из колонки 5 выгрузки 1С (для информации)', max_length=200, verbose_name='Факультет, курс, группа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_load_items', to='core.teachingactivitytype', verbose_name='Вид занятия')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_load', to='accounts.teacherposition', verbose_name='Позиция преподавателя')),
            ],
            options={
                'verbose_name': 'Строка учебной нагрузки',
                'verbose_name_plural': 'Строки учебной нагрузки',
                'ordering': ['position', 'semester', 'discipline', 'activity_type__sort_order'],
            },
        ),
    ]
