# Generated by Django 5.2.12 on 2026-06-08 20:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_teachingloaditem_new_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingloaditem',
            name='cycle',
            field=models.CharField(blank=True, default='', help_text='Например: «Б1.О.23». Из полного плана (col9).', max_length=200, verbose_name='Цикл дисциплины'),
        ),
        migrations.AlterField(
            model_name='teachingloaditem',
            name='group_number',
            field=models.CharField(blank=True, default='', help_text='Из колонки 11 полного плана или колонки 5 legacy-выгрузки (для информации)', max_length=500, verbose_name='Факультет, курс, группа'),
        ),
        migrations.AlterField(
            model_name='teachingloaditem',
            name='hours_fact',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Фактически выполненные часы. По умолчанию 0.', max_digits=7, verbose_name='Часы (факт)'),
        ),
        migrations.AlterField(
            model_name='teachingloaditem',
            name='students_count',
            field=models.PositiveIntegerField(blank=True, help_text='Из полного плана (col13).', null=True, verbose_name='Число студентов'),
        ),
    ]
