# Generated by Django 5.2.12 on 2026-06-10 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_teachingloaditem_period_label_row_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherposition',
            name='protocol_date',
        ),
        migrations.RemoveField(
            model_name='teacherposition',
            name='protocol_number',
        ),
    ]
