# Generated by Django 5.2.12 on 2026-06-18 15:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_protocol_from_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherposition',
            name='teaching_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Заполняется по выгрузке из 1С.', max_digits=7, verbose_name='Учебная нагрузка (часов из 1С)'),
        ),
        migrations.AlterField(
            model_name='teachingloaditem',
            name='hours_fact',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Фактически выполненные часы. По умолчанию 0.', max_digits=7, verbose_name='Часы (факт)'),
        ),
    ]
