# Generated by Django 5.2.12 on 2026-03-11 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: 2025-2026', max_length=20, unique=True, verbose_name='Название')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=False, help_text='Только один учебный год может быть активным', verbose_name='Активный')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архивный')),
            ],
            options={
                'verbose_name': 'Учебный год',
                'verbose_name_plural': 'Учебные годы',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Название кафедры')),
                ('short_name', models.CharField(blank=True, default='', max_length=50, verbose_name='Сокращённое название')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название должности')),
                ('code', models.CharField(choices=[('DEAN', 'Декан'), ('HEAD_OF_DEPARTMENT', 'Заведующий кафедрой'), ('PROFESSOR', 'Профессор'), ('ASSOCIATE_PROFESSOR', 'Доцент'), ('SENIOR_TEACHER', 'Старший преподаватель'), ('ASSISTANT', 'Ассистент')], max_length=30, unique=True, verbose_name='Код должности')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('code', models.CharField(choices=[('TEACHING', 'Учебная работа'), ('EDUCATIONAL_METHODICAL', 'Учебно-методическая'), ('SCIENTIFIC', 'Научно-исследовательская'), ('ORGANIZATIONAL', 'Организационно-методическая'), ('EDUCATIONAL_WORK', 'Воспитательная работа')], max_length=30, unique=True, verbose_name='Код категории')),
                ('description', models.TextField(blank=True, default='', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория задач',
                'verbose_name_plural': 'Категории задач',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PositionWorkload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_teaching_hours', models.PositiveIntegerField(help_text='Верхний предел учебной нагрузки для ставки 1.0', verbose_name='Макс. учебных часов (на полную ставку)')),
                ('max_total_hours', models.PositiveIntegerField(default=1550, help_text='По умолчанию 1550 часов', verbose_name='Общий объём рабочего времени (часов в год)')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workloads', to='core.academicyear', verbose_name='Учебный год')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workloads', to='core.position', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Норма нагрузки',
                'verbose_name_plural': 'Нормы нагрузки',
                'ordering': ['academic_year', 'position'],
                'unique_together': {('position', 'academic_year')},
            },
        ),
    ]
