# Generated by Django 5.2.12 on 2026-05-06 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: «Разработка рабочей программы дисциплины»', max_length=255, verbose_name='Название вида работы')),
                ('max_hours', models.PositiveIntegerField(help_text='Верхний предел часов согласно нормативу ВГТУ', verbose_name='Максимум часов')),
                ('unit_description', models.CharField(blank=True, default='', help_text='Например: «на одну дисциплину», «за 1 печатный лист», «в год»', max_length=200, verbose_name='Единица измерения / уточнение')),
                ('is_active', models.BooleanField(default=True, help_text='Неактивные виды не показываются при создании задач', verbose_name='Активен')),
                ('category', models.ForeignKey(help_text='Категория, к которой относится этот вид работы', on_delete=django.db.models.deletion.PROTECT, related_name='work_types', to='core.taskcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Вид работы',
                'verbose_name_plural': 'Виды работ (справочник)',
                'ordering': ['category', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
    ]
