# Generated by Django 5.2.12 on 2026-05-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_worktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: «Лекционные занятия», «Экзамен»', max_length=200, unique=True, verbose_name='Название вида занятия')),
                ('code', models.CharField(help_text='Короткий ASCII-идентификатор для парсера. Например: LECTURE, EXAM, COURSE_WORK', max_length=40, unique=True, verbose_name='Код')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Чем меньше число, тем выше в списке', verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Вид учебного занятия',
                'verbose_name_plural': 'Виды учебных занятий',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
