# Generated by Django 5.2.12 on 2026-06-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_categorylimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylimit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
