# Generated by Django 5.2.12 on 2026-06-10 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_categorylimit_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(blank=True, default='', help_text='Например: «Компьютерных интеллектуальных технологий проектирования»', max_length=300, verbose_name='Название кафедры')),
                ('faculty_name', models.CharField(blank=True, default='', help_text='Например: «Факультет информационных технологий и компьютерной безопасности»', max_length=300, verbose_name='Название факультета')),
                ('approver_title', models.CharField(blank=True, default='', help_text='Например: «Декан факультета ИТ и КБ»', max_length=300, verbose_name='Должность утверждающего')),
                ('approver_name', models.CharField(blank=True, default='', help_text='Например: «Иванов И.И.»', max_length=255, verbose_name='ФИО утверждающего')),
                ('head_name', models.CharField(blank=True, default='', help_text='Для подписи в документе', max_length=255, verbose_name='ФИО заведующего кафедрой')),
                ('protocol_number', models.CharField(blank=True, default='', help_text='Если не заполнено — в документе будет плейсхолдер', max_length=50, verbose_name='Номер протокола')),
                ('protocol_date', models.DateField(blank=True, help_text='Если не заполнено — в документе будет плейсхолдер', null=True, verbose_name='Дата протокола')),
                ('academic_year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='export_settings', to='core.academicyear', verbose_name='Учебный год')),
            ],
            options={
                'verbose_name': 'Настройки выгрузки',
                'verbose_name_plural': 'Настройки выгрузки',
            },
        ),
    ]
