# Generated by Django 5.2.12 on 2026-06-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_canonical_work_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktype',
            name='is_per_unit',
            field=models.BooleanField(default=False, help_text='Если включено, норматив max_hours указан «за один объект» (работа, статья, программа, мероприятие). Тогда одна задача в системе может содержать несколько таких единиц — превышение norm в задаче допустимо. Если выключено, норматив указан «в год» или «на позицию» — превышение блокируется.', verbose_name='Норматив на единицу'),
        ),
        migrations.AlterField(
            model_name='exportsettings',
            name='approver_name',
            field=models.CharField(blank=True, default='', help_text='Например: «И.И.Иванов »', max_length=255, verbose_name='ФИО утверждающего'),
        ),
        migrations.AlterField(
            model_name='exportsettings',
            name='approver_title',
            field=models.CharField(blank=True, default='', help_text='Например: «Декан»', max_length=300, verbose_name='Должность утверждающего'),
        ),
        migrations.AlterField(
            model_name='exportsettings',
            name='department_full_name',
            field=models.CharField(blank=True, default='', help_text='В родительном падеже, например: «Компьютерных интеллектуальных технологий проектирования»', max_length=300, verbose_name='Полное название кафедры'),
        ),
        migrations.AlterField(
            model_name='exportsettings',
            name='department_name',
            field=models.CharField(blank=True, default='', help_text='Аббревиатура, например: «КИТП»', max_length=300, verbose_name='Название кафедры'),
        ),
        migrations.AlterField(
            model_name='exportsettings',
            name='protocol_date',
            field=models.DateField(blank=True, help_text='Если не заполнено — в документе будет плейсхолдер', null=True, verbose_name='Дата протокола(план)'),
        ),
        migrations.AlterField(
            model_name='exportsettings',
            name='protocol_number',
            field=models.CharField(blank=True, default='', help_text='Если не заполнено — в документе будет плейсхолдер', max_length=50, verbose_name='Номер протокола(план)'),
        ),
    ]
